<<<<<<< HEAD
<<<<<<< HEAD
# Site
title: Ross Muego
description: Software Engineering
url: https://rossmuego.com
logo: halve.png # Site logo
locale: en_US

# Left Block Images
background:
  homepage: images/cover.jpg # this image will be shown on homepage's left block
  post-list: images/unsplash-image-10.jpg # this image will be shown on post list page
  default-post: images/unsplash-gallery-image-3.jpg # this image will be shown when post's front matter doesn't specify any image

# Jekyll
permalink: /:title/
markdown: kramdown
highlighter: rouge
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
sass:
  sass_dir: assets/_sass
  style: compressed
=======
# Site settings
title: 'Ross Muego'
description: 'Computer Science Student'
url: 'rossmuego.com'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'
=======
# Site
title: Halve
description: Stylish, Two-Column Jekyll Theme
url: https://taylantatli.github.io/Halve
logo: halve.png                                       # Site logo
locale: en_US
>>>>>>> 076c16e... changed theme

# Left Block Images
background:
  homepage: images/home.png                           # this image will be shown on homepage's left block
  post-list: images/unsplash-image-10.jpg             # this image will be shown on post list page
  default-post: images/unsplash-gallery-image-3.jpg   # this image will be shown when post's front matter doesn't specify any image

<<<<<<< HEAD
defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'
>>>>>>> parent of 076c16e... changed theme
=======
# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
sass:
  sass_dir:         assets/_sass
  style:            compressed
>>>>>>> 076c16e... changed theme

# Google Analytics
#google-analytics: UA-XXXXX-Y

<<<<<<< HEAD
<<<<<<< HEAD
# Social Links
email: rossmuego@gmail.com
#google.plus:        username
#twitter:            username
#facebook:           username
github: rossmuego
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin: ross-muego-523232140
#xing:              username
#instagram:          username
#lastfm:            username
#tumblr: username
=======
# Social Links
#email:             email
#google.plus:        username
twitter:            username
#facebook:           username
github:             username
stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          username
#xing:              username
#instagram:          username
#lastfm:            username
#tumblr:            username
>>>>>>> 076c16e... changed theme
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username
<<<<<<< HEAD
#behance:           username
=======
sass:
    sass_dir: _sass
    style: compressed
>>>>>>> parent of 076c16e... changed theme
=======
behance:           username
>>>>>>> 076c16e... changed theme

# Gems
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

<<<<<<< HEAD
<<<<<<< HEAD
# Exclude list
include: [_pages]
exclude:
  [
    README.md,
    Gemfile,
    Gemfile.lock,
    _site,
    src,
    vendor,
    CNAME,
    LICENSE,
    Rakefile,
    .sass-cache,
    .DS_Store,
  ]
=======
gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
>>>>>>> parent of 076c16e... changed theme
=======
# Exclude list
include: [_pages]
exclude: [README.md, Gemfile, Gemfile.lock, _site, src, vendor, CNAME, LICENSE, Rakefile, .sass-cache, .DS_Store]
>>>>>>> 076c16e... changed theme
